// <auto-generated />
using System;
using DisciplineSwitcher.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DisciplineSwitcher.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230610151533_AddConcurrencyStampForTestUsers")]
    partial class AddConcurrencyStampForTestUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DisciplineGroup", b =>
                {
                    b.Property<Guid>("DisciplinesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupsId")
                        .HasColumnType("uuid");

                    b.HasKey("DisciplinesId", "GroupsId");

                    b.HasIndex("GroupsId");

                    b.ToTable("DisciplineGroup");
                });

            modelBuilder.Entity("DisciplineSwitcher.Domain.Entities.Discipline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SemesterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SemesterId");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("DisciplineSwitcher.Domain.Entities.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("DisciplineSwitcher.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("DisciplineSwitcher.Domain.Entities.Semester", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("GroupTeacher", b =>
                {
                    b.Property<Guid>("GroupsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeachersId")
                        .HasColumnType("uuid");

                    b.HasKey("GroupsId", "TeachersId");

                    b.HasIndex("TeachersId");

                    b.ToTable("GroupTeacher");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d522e6ae-a0d5-4753-8bf1-feb30e3b535e"),
                            ConcurrencyStamp = "829d1889-42d0-4f86-bac0-a7a32cb6cf61",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("7a7231fb-fe42-40df-bf8b-1adcb564a136"),
                            ConcurrencyStamp = "80b452b2-6e63-4f8b-aab7-58f424940b2a",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        },
                        new
                        {
                            Id = new Guid("104adc6e-eb7e-40ee-832c-64b2198b0e6f"),
                            ConcurrencyStamp = "6bde5916-de4c-4455-afe8-c4a48b0840bd",
                            Name = "Teacher",
                            NormalizedName = "TEACHER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 49,
                            ClaimType = "get:student",
                            RoleId = new Guid("d522e6ae-a0d5-4753-8bf1-feb30e3b535e")
                        },
                        new
                        {
                            Id = 50,
                            ClaimType = "create:student",
                            RoleId = new Guid("d522e6ae-a0d5-4753-8bf1-feb30e3b535e")
                        },
                        new
                        {
                            Id = 51,
                            ClaimType = "delete:student",
                            RoleId = new Guid("d522e6ae-a0d5-4753-8bf1-feb30e3b535e")
                        },
                        new
                        {
                            Id = 52,
                            ClaimType = "update:student",
                            RoleId = new Guid("d522e6ae-a0d5-4753-8bf1-feb30e3b535e")
                        },
                        new
                        {
                            Id = 53,
                            ClaimType = "get:teacher",
                            RoleId = new Guid("d522e6ae-a0d5-4753-8bf1-feb30e3b535e")
                        },
                        new
                        {
                            Id = 54,
                            ClaimType = "create:teacher",
                            RoleId = new Guid("d522e6ae-a0d5-4753-8bf1-feb30e3b535e")
                        },
                        new
                        {
                            Id = 55,
                            ClaimType = "delete:teacher",
                            RoleId = new Guid("d522e6ae-a0d5-4753-8bf1-feb30e3b535e")
                        },
                        new
                        {
                            Id = 56,
                            ClaimType = "update:teacher",
                            RoleId = new Guid("d522e6ae-a0d5-4753-8bf1-feb30e3b535e")
                        },
                        new
                        {
                            Id = 57,
                            ClaimType = "get:discipline",
                            RoleId = new Guid("d522e6ae-a0d5-4753-8bf1-feb30e3b535e")
                        },
                        new
                        {
                            Id = 58,
                            ClaimType = "create:discipline",
                            RoleId = new Guid("d522e6ae-a0d5-4753-8bf1-feb30e3b535e")
                        },
                        new
                        {
                            Id = 59,
                            ClaimType = "delete:discipline",
                            RoleId = new Guid("d522e6ae-a0d5-4753-8bf1-feb30e3b535e")
                        },
                        new
                        {
                            Id = 60,
                            ClaimType = "update:discipline",
                            RoleId = new Guid("d522e6ae-a0d5-4753-8bf1-feb30e3b535e")
                        },
                        new
                        {
                            Id = 61,
                            ClaimType = "get:faculty",
                            RoleId = new Guid("d522e6ae-a0d5-4753-8bf1-feb30e3b535e")
                        },
                        new
                        {
                            Id = 62,
                            ClaimType = "create:faculty",
                            RoleId = new Guid("d522e6ae-a0d5-4753-8bf1-feb30e3b535e")
                        },
                        new
                        {
                            Id = 63,
                            ClaimType = "delete:faculty",
                            RoleId = new Guid("d522e6ae-a0d5-4753-8bf1-feb30e3b535e")
                        },
                        new
                        {
                            Id = 64,
                            ClaimType = "update:faculty",
                            RoleId = new Guid("d522e6ae-a0d5-4753-8bf1-feb30e3b535e")
                        },
                        new
                        {
                            Id = 65,
                            ClaimType = "get:semester",
                            RoleId = new Guid("d522e6ae-a0d5-4753-8bf1-feb30e3b535e")
                        },
                        new
                        {
                            Id = 66,
                            ClaimType = "create:semester",
                            RoleId = new Guid("d522e6ae-a0d5-4753-8bf1-feb30e3b535e")
                        },
                        new
                        {
                            Id = 67,
                            ClaimType = "delete:semester",
                            RoleId = new Guid("d522e6ae-a0d5-4753-8bf1-feb30e3b535e")
                        },
                        new
                        {
                            Id = 68,
                            ClaimType = "update:semester",
                            RoleId = new Guid("d522e6ae-a0d5-4753-8bf1-feb30e3b535e")
                        },
                        new
                        {
                            Id = 69,
                            ClaimType = "get:group",
                            RoleId = new Guid("d522e6ae-a0d5-4753-8bf1-feb30e3b535e")
                        },
                        new
                        {
                            Id = 70,
                            ClaimType = "create:group",
                            RoleId = new Guid("d522e6ae-a0d5-4753-8bf1-feb30e3b535e")
                        },
                        new
                        {
                            Id = 71,
                            ClaimType = "delete:group",
                            RoleId = new Guid("d522e6ae-a0d5-4753-8bf1-feb30e3b535e")
                        },
                        new
                        {
                            Id = 72,
                            ClaimType = "get:student",
                            RoleId = new Guid("104adc6e-eb7e-40ee-832c-64b2198b0e6f")
                        },
                        new
                        {
                            Id = 73,
                            ClaimType = "update:student",
                            RoleId = new Guid("104adc6e-eb7e-40ee-832c-64b2198b0e6f")
                        },
                        new
                        {
                            Id = 74,
                            ClaimType = "get:teacher",
                            RoleId = new Guid("104adc6e-eb7e-40ee-832c-64b2198b0e6f")
                        },
                        new
                        {
                            Id = 75,
                            ClaimType = "create:teacher",
                            RoleId = new Guid("104adc6e-eb7e-40ee-832c-64b2198b0e6f")
                        },
                        new
                        {
                            Id = 76,
                            ClaimType = "update:teacher",
                            RoleId = new Guid("104adc6e-eb7e-40ee-832c-64b2198b0e6f")
                        },
                        new
                        {
                            Id = 77,
                            ClaimType = "delete:teacher",
                            RoleId = new Guid("104adc6e-eb7e-40ee-832c-64b2198b0e6f")
                        },
                        new
                        {
                            Id = 78,
                            ClaimType = "get:discipline",
                            RoleId = new Guid("104adc6e-eb7e-40ee-832c-64b2198b0e6f")
                        },
                        new
                        {
                            Id = 79,
                            ClaimType = "create:discipline",
                            RoleId = new Guid("104adc6e-eb7e-40ee-832c-64b2198b0e6f")
                        },
                        new
                        {
                            Id = 80,
                            ClaimType = "update:discipline",
                            RoleId = new Guid("104adc6e-eb7e-40ee-832c-64b2198b0e6f")
                        },
                        new
                        {
                            Id = 81,
                            ClaimType = "delete:discipline",
                            RoleId = new Guid("104adc6e-eb7e-40ee-832c-64b2198b0e6f")
                        },
                        new
                        {
                            Id = 82,
                            ClaimType = "get:faculty",
                            RoleId = new Guid("104adc6e-eb7e-40ee-832c-64b2198b0e6f")
                        },
                        new
                        {
                            Id = 83,
                            ClaimType = "get:semester",
                            RoleId = new Guid("104adc6e-eb7e-40ee-832c-64b2198b0e6f")
                        },
                        new
                        {
                            Id = 84,
                            ClaimType = "get:group",
                            RoleId = new Guid("104adc6e-eb7e-40ee-832c-64b2198b0e6f")
                        },
                        new
                        {
                            Id = 85,
                            ClaimType = "create:group",
                            RoleId = new Guid("104adc6e-eb7e-40ee-832c-64b2198b0e6f")
                        },
                        new
                        {
                            Id = 86,
                            ClaimType = "update:group",
                            RoleId = new Guid("104adc6e-eb7e-40ee-832c-64b2198b0e6f")
                        },
                        new
                        {
                            Id = 87,
                            ClaimType = "delete:group",
                            RoleId = new Guid("104adc6e-eb7e-40ee-832c-64b2198b0e6f")
                        },
                        new
                        {
                            Id = 88,
                            ClaimType = "get:student",
                            RoleId = new Guid("7a7231fb-fe42-40df-bf8b-1adcb564a136")
                        },
                        new
                        {
                            Id = 89,
                            ClaimType = "create:student",
                            RoleId = new Guid("7a7231fb-fe42-40df-bf8b-1adcb564a136")
                        },
                        new
                        {
                            Id = 90,
                            ClaimType = "delete:student",
                            RoleId = new Guid("7a7231fb-fe42-40df-bf8b-1adcb564a136")
                        },
                        new
                        {
                            Id = 91,
                            ClaimType = "update:student",
                            RoleId = new Guid("7a7231fb-fe42-40df-bf8b-1adcb564a136")
                        },
                        new
                        {
                            Id = 92,
                            ClaimType = "get:teacher",
                            RoleId = new Guid("7a7231fb-fe42-40df-bf8b-1adcb564a136")
                        },
                        new
                        {
                            Id = 93,
                            ClaimType = "get:discipline",
                            RoleId = new Guid("7a7231fb-fe42-40df-bf8b-1adcb564a136")
                        },
                        new
                        {
                            Id = 94,
                            ClaimType = "get:faculty",
                            RoleId = new Guid("7a7231fb-fe42-40df-bf8b-1adcb564a136")
                        },
                        new
                        {
                            Id = 95,
                            ClaimType = "get:semester",
                            RoleId = new Guid("7a7231fb-fe42-40df-bf8b-1adcb564a136")
                        },
                        new
                        {
                            Id = 96,
                            ClaimType = "get:group",
                            RoleId = new Guid("7a7231fb-fe42-40df-bf8b-1adcb564a136")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.UseTptMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = new Guid("672979c9-d851-4bb7-83b6-a75e906dbefa"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f47de272-e977-45e9-9417-fd0182864796",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEGqETzbybD5drWa3xOiQPQ6J8TBgcA1iJxK/zv9SdvFvTZmr9xsLp34FLI0669zdnQ==",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("672979c9-d851-4bb7-83b6-a75e906dbefa"),
                            RoleId = new Guid("d522e6ae-a0d5-4753-8bf1-feb30e3b535e")
                        },
                        new
                        {
                            UserId = new Guid("bebdddb7-27ab-4513-8ba7-a3eefcc7772b"),
                            RoleId = new Guid("104adc6e-eb7e-40ee-832c-64b2198b0e6f")
                        },
                        new
                        {
                            UserId = new Guid("537826d9-90b5-4d70-9606-addbd078d509"),
                            RoleId = new Guid("7a7231fb-fe42-40df-bf8b-1adcb564a136")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DisciplineSwitcher.Domain.Entities.Student", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>");

                    b.Property<Guid?>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.HasIndex("FacultyId");

                    b.HasIndex("GroupId");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("537826d9-90b5-4d70-9606-addbd078d509"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7aa5ed02-b8ec-4120-b0f8-b09285ea67a0",
                            Email = "artur.bondar@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEBUiQFHISQ6SZvKzvUPmmTRSzB5hDGBJeceptv8JQGMIAYuxB5U6zkfqj5/loMtUkw==",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = false,
                            UserName = "Artur Bondar"
                        });
                });

            modelBuilder.Entity("DisciplineSwitcher.Domain.Entities.Teacher", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>");

                    b.Property<Guid?>("FacultyId")
                        .HasColumnType("uuid");

                    b.HasIndex("FacultyId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bebdddb7-27ab-4513-8ba7-a3eefcc7772b"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6d056582-a252-4af0-97a9-35f0d40d9608",
                            Email = "volodymyr.tymofiyovych@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEOBlFkRyysZFYj9Ujtj6hRfipJMduRKvsxZT6fGhWkvI0Qzow2zOBD49+Zitk9KzTw==",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = false,
                            UserName = "Volodymyr Tymofiyovych"
                        });
                });

            modelBuilder.Entity("DisciplineGroup", b =>
                {
                    b.HasOne("DisciplineSwitcher.Domain.Entities.Discipline", null)
                        .WithMany()
                        .HasForeignKey("DisciplinesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DisciplineSwitcher.Domain.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DisciplineSwitcher.Domain.Entities.Discipline", b =>
                {
                    b.HasOne("DisciplineSwitcher.Domain.Entities.Semester", "Semester")
                        .WithMany("Disciplines")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("DisciplineSwitcher.Domain.Entities.Group", b =>
                {
                    b.HasOne("DisciplineSwitcher.Domain.Entities.Faculty", "Faculty")
                        .WithMany("Groups")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("GroupTeacher", b =>
                {
                    b.HasOne("DisciplineSwitcher.Domain.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DisciplineSwitcher.Domain.Entities.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeachersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DisciplineSwitcher.Domain.Entities.Student", b =>
                {
                    b.HasOne("DisciplineSwitcher.Domain.Entities.Faculty", null)
                        .WithMany("Students")
                        .HasForeignKey("FacultyId");

                    b.HasOne("DisciplineSwitcher.Domain.Entities.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithOne()
                        .HasForeignKey("DisciplineSwitcher.Domain.Entities.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("DisciplineSwitcher.Domain.Entities.Teacher", b =>
                {
                    b.HasOne("DisciplineSwitcher.Domain.Entities.Faculty", null)
                        .WithMany("Teachers")
                        .HasForeignKey("FacultyId");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithOne()
                        .HasForeignKey("DisciplineSwitcher.Domain.Entities.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DisciplineSwitcher.Domain.Entities.Faculty", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Students");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("DisciplineSwitcher.Domain.Entities.Group", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("DisciplineSwitcher.Domain.Entities.Semester", b =>
                {
                    b.Navigation("Disciplines");
                });
#pragma warning restore 612, 618
        }
    }
}
